$\newcommand{\RE}{\mathrm{Re}}$
$\newcommand{\IM}{\mathrm{Im}}$
$\newcommand{\D}{\mathcal{D}}$
$\newcommand{\E}{\mathcal{E}}$
$\newcommand{\G}{\Gamma}$
$\newcommand{\OG}{\Gamma^\dagger}$

In [3]:
collect(0.5:1.0:(10-0.5))

10-element Vector{Float64}:
 0.5
 1.5
 2.5
 3.5
 4.5
 5.5
 6.5
 7.5
 8.5
 9.5

In [1]:
from scipy.optimize import least_squares
import numpy as np

In [3]:
np.exp(1)

2.718281828459045

In [4]:
2*np.arange(11)-np.exp(np.arange(11)*1)

array([-1.00000000e+00, -7.18281828e-01, -3.38905610e+00, -1.40855369e+01,
       -4.65981500e+01, -1.38413159e+02, -3.91428793e+02, -1.08263316e+03,
       -2.96495799e+03, -8.08508393e+03, -2.20064658e+04])

In [5]:
def myfun(x):
    k = np.arange(11)
    return 2*k-np.exp(k*x[0]) - np.exp(k*x[1])       

In [7]:
res_1 = least_squares(myfun, np.array([0.3,0.4]))
res_1.x

array([0.24532273, 0.24531671])

In [8]:
res_1.cost

29.04688054837413

In [9]:
res_1.optimality

0.004234346536918565

In [10]:
res_1.status

2

In [13]:
np.linalg.norm(myfun(np.array([0.2578,0.2578])), 2)

8.764461601900072

    Updating registry at `C:\Users\Kamlesh\.julia\registries\General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
   Installed OptimBase ─ v2.0.2
   Installed LsqFit ──── v0.12.1
    Updating `C:\Users\Kamlesh\.julia\environments\v1.7\Project.toml`
  [2fda8390] + LsqFit v0.12.1
    Updating `C:\Users\Kamlesh\.julia\environments\v1.7\Manifest.toml`
  [2fda8390] + LsqFit v0.12.1
  [87e2bd06] + OptimBase v2.0.2
Precompiling project...
  ✓ OptimBase
  ✓ LsqFit
  2 dependencies successfully precompiled in 7 seconds (320 already precompiled)


In [3]:
using LsqFit

In [14]:
g(κ, ζ) = κ[1] * exp.(κ[2] * ζ)

g (generic function with 1 method)

In [19]:
g([1,1],[0,1])

2-element Vector{Float64}:
 1.0
 2.718281828459045

In [16]:
κ0 = [0.5, 0.5]
ydata = [0 , 0]
ζdata = Array{Float64}[]
for i=1:2
    push!(ζdata,[i,i])
end

ζdata
#fit = curve_fit(g, ζdata, ydata, κ0)

2-element Vector{Array{Float64}}:
 [1.0, 1.0]
 [2.0, 2.0]

In [17]:
fit = curve_fit(g, ζdata, ydata, κ0)

LoadError: MethodError: no method matching isinf(::Vector{Float64})
Closest candidates are:
  isinf(::Complex) at C:\Users\Kamlesh\AppData\Local\Programs\julia-1.7.2\share\julia\base\complex.jl:148
  isinf(::DualNumbers.Dual) at C:\Users\Kamlesh\.julia\packages\DualNumbers\ULBIj\src\dual.jl:53
  isinf(::ForwardDiff.Dual) at C:\Users\Kamlesh\.julia\packages\ForwardDiff\PBzup\src\dual.jl:336
  ...

# ADNLP API

In [21]:
import Pkg
Pkg.add("NLPModels")

   Resolving package versions...
   Installed NLPModels ─ v0.18.3
    Updating `C:\Users\Kamlesh\.julia\environments\v1.7\Project.toml`
  [a4795742] + NLPModels v0.18.3
    Updating `C:\Users\Kamlesh\.julia\environments\v1.7\Manifest.toml`
  [a4795742] + NLPModels v0.18.3
Precompiling project...
  ✓ NLPModels
  1 dependency successfully precompiled in 3 seconds (322 already precompiled)


In [1]:
using NLPModels

In [4]:
AbstractNLSModel <: AbstractNLPModel

true

In [18]:
import Pkg
Pkg.add("ADNLPModels")

   Resolving package versions...
   Installed ADNLPModels ─ v0.3.1
    Updating `C:\Users\Kamlesh\.julia\environments\v1.7\Project.toml`
  [54578032] + ADNLPModels v0.3.1
    Updating `C:\Users\Kamlesh\.julia\environments\v1.7\Manifest.toml`
  [54578032] + ADNLPModels v0.3.1
Precompiling project...
  ✓ ADNLPModels
  1 dependency successfully precompiled in 8 seconds (323 already precompiled)


In [1]:
using ADNLPModels,  LsqFit

In [2]:
#using rosenbrock function to define the nonlinear least squares objective

F(x) = [x[1] - 1.0; 10 * (x[2] - x[1]^2)]
x0 = [-1.2; 1.0]
nls = ADNLSModel(F, x0, 2) # 2 nonlinear equations

LoadError: MethodError: no method matching ADNLSModel(::typeof(F), ::Vector{Float64})
Closest candidates are:
  ADNLSModel(::Any, ::S, ::Integer; linequ, name, adbackend) where S at C:\Users\Kamlesh\.julia\packages\ADNLPModels\9yjtG\src\nls.jl:43
  ADNLSModel(::Any, ::S, ::Integer, ::S, ::S; linequ, name, adbackend) where S at C:\Users\Kamlesh\.julia\packages\ADNLPModels\9yjtG\src\nls.jl:61
  ADNLSModel(::Any, ::S, ::Integer, ::S, ::S, ::Any, ::S, ::S; y0, lin, linequ, name, adbackend) where S at C:\Users\Kamlesh\.julia\packages\ADNLPModels\9yjtG\src\nls.jl:118
  ...

In [15]:
rand(Float64, 10)

10-element Vector{Float64}:
 0.13556320842455183
 0.532682955885541
 0.175466572037158
 0.8058867855949021
 0.26168351948401436
 0.36145613010115296
 0.7163955140840705
 0.2521181964978694
 0.8595842558337334
 0.06660440911282561

In [12]:
fit = LsqFit.lmfit(F, [-1.2; 1.0], Float64[])

LsqFit.LsqFitResult{Vector{Float64}, Vector{Float64}, Matrix{Float64}, Vector{Float64}}([0.9999999999988214, 0.9999999999976396], [-1.1786127629420662e-12, -3.219646771412954e-14], [0.9999999999960525 0.0; -19.999999999829377 10.000000000052196], true, Float64[])

In [10]:
fit.jacobian

2×2 Matrix{Float64}:
   1.0   0.0
 -20.0  10.0

In [25]:
Pkg.add("JuMP")

   Resolving package versions...
   Installed CodecBzip2 ─────── v0.7.2
   Installed JuMP ───────────── v1.0.0
   Installed MathOptInterface ─ v1.1.2
    Updating `C:\Users\Kamlesh\.julia\environments\v1.7\Project.toml`
  [4076af6c] + JuMP v1.0.0
    Updating `C:\Users\Kamlesh\.julia\environments\v1.7\Manifest.toml`
  [523fee87] + CodecBzip2 v0.7.2
  [4076af6c] + JuMP v1.0.0
  [b8f27783] + MathOptInterface v1.1.2
Precompiling project...
  ✓ CodecBzip2
  ✓ MathOptInterface
  ✓ JuMP
  3 dependencies successfully precompiled in 39 seconds (324 already precompiled)


In [27]:
Pkg.add("NLPModelsJuMP")

   Resolving package versions...
   Installed NLPModelsJuMP ─ v0.10.1
    Updating `C:\Users\Kamlesh\.julia\environments\v1.7\Project.toml`
  [792afdf1] + NLPModelsJuMP v0.10.1
    Updating `C:\Users\Kamlesh\.julia\environments\v1.7\Manifest.toml`
  [792afdf1] + NLPModelsJuMP v0.10.1
Precompiling project...
  ✓ NLPModelsJuMP
  1 dependency successfully precompiled in 6 seconds (327 already precompiled)


In [28]:
using JuMP, NLPModelsJuMP

In [31]:
model = Model()
x0 = [-1.2; 1.0]
@variable(model, x[i=1:2], start=x0[i])

@NLexpression(model, F1, x[1]-1)
@NLexpression(model, F2, 10 * (x[2] - x[1]^2))

nls = MathOptNLSModel(model, [F1, F2], name="rosenbrock-nls")

MathOptNLSModel
  Problem name: rosenbrock-nls
   All variables: ████████████████████ 2      All constraints: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0        All residuals: ████████████████████ 2     
            free: ████████████████████ 2                 free: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0               linear: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0     
           lower: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                lower: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0            nonlinear: ████████████████████ 2     
           upper: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                upper: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                 nnzj: ( 25.00% sparsity)   3     
         low/upp: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0              low/upp: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                 nnzh: ( 66.67% sparsity)   1     
           fixed: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                fixed: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0     
          infeas: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0               infeas: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0     
            nnzh: (  0.00% sparsity)   3               linear: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0     


In [33]:
Pkg.add("JSOSolvers")

   Resolving package versions...
   Installed SolverTools ──────── v0.8.0
   Installed NLPModelsModifiers ─ v0.5.1
   Installed JSOSolvers ───────── v0.7.6
   Installed SolverCore ───────── v0.2.2
   Installed Krylov ───────────── v0.7.13
    Updating `C:\Users\Kamlesh\.julia\environments\v1.7\Project.toml`
  [10dff2fc] + JSOSolvers v0.7.6
    Updating `C:\Users\Kamlesh\.julia\environments\v1.7\Manifest.toml`
  [10dff2fc] + JSOSolvers v0.7.6
  [ba0b0d4f] + Krylov v0.7.13
  [e01155f1] + NLPModelsModifiers v0.5.1
  [ff4d7338] + SolverCore v0.2.2
  [b5612192] + SolverTools v0.8.0
Precompiling project...
  ✓ SolverTools
  ✓ SolverCore
  ✓ NLPModelsModifiers
  ✓ Krylov
  ✓ JSOSolvers
  5 dependencies successfully precompiled in 4 seconds (328 already precompiled)


In [3]:
using JSOSolvers

output = trunk(nls)

"Execution stats: first-order stationary"

In [4]:
print(output)

Generic Execution stats
  status: first-order stationary
  objective value: 7.99609381573681e-20
  primal feasibility: 0.0
  dual feasibility: 8.942088019996678e-9
  solution: [1.0  0.9999999999600098]
  iterations: 19
  elapsed time: 2.5859999656677246


In [5]:
output.solution

2-element Vector{Float64}:
 1.0
 0.9999999999600098

In [35]:
print(output)

Generic Execution stats
  status: first-order stationary
  objective value: 7.99609381573681e-20
  primal feasibility: 0.0
  dual feasibility: 8.942088019996678e-9
  solution: [1.0  0.9999999999600098]
  iterations: 19
  elapsed time: 2.2360000610351562


# Notations
1. $\underline{{N_I},{N_k}}$ - $N_I$ is the number of RF sequence pulses. This is also the number of snapshot images acquired during MRF. $N_k$ is the number of $k$-space sampling locations.<br><br> 

2. $\underline{j}$ - refers to the $j^{\text{th}}$ snapshot.<br><br>

3. $\underline{\theta}$ - a vector of *true tissue* parameters on which the magnetization depends. The length of $\theta$ is given as $n$ but is usually restricted to $3$ referring to the parameters $T_1, T_2$ relaxation times and the proton density, $\rho$. <br><br>

4. $\underline{\theta^*}$ - *reconstructed* parameters with MRF.<br><br>

5. $\underline{\theta_1, \theta_1^*}$ - contrast terms in true and reconstructed parameters respectively.<br><br>

6. $\underline{T_R, T_E, \alpha, \phi}$ - *experimental* parameters that refer to the repetition time ($T_R$), echo time ($T_E$), flip angle ($\alpha$) and phase ($\phi$).<br><br>

7. $\underline{\boldsymbol{x, \zeta}}$   - $\boldsymbol x$ and $\boldsymbol\zeta$ refer to the coordinates in the spatial and $k$-space grid respectively. <br><br>

8. $\underline{M_j(\theta)}$ - magnetization at the j<sup>th</sup> snapshot which is function of the tissue parameters $\theta$. <br><br>

9. $\underline{\boldsymbol \kappa}$ - a vector of scaling factors; element $\kappa_j$ refers to the scaling factor for the j<sup>th</sup> snapshot. <br><br>

10. $\underline{P_j(x), P(x)}$ - $P_j(x)$ refers to the point-spread function associated with j<sup>th</sup> snapshot and $P(x)$ refers to the average PSF given by $P(x)=\frac{1}{N_I}\sum\limits_{j=1}^{N_I}P_j(x)$. <br><br>

11. $\underline{\D M(\theta)_j}$ - jacobian of $M_j(\theta)$. The components of jacobian are denoted as $\D M(\theta)_{j;p}$. Note that the subscripts $p,q,r$ always refer to the position of elements in a matrix. If the matrix is a Jacobian then the position also refers to the parameter w.r.t which the partial derivative was taken. <br><br>

12. $\underline{\widehat{f}}$ - denotes the Fourier transform of a function $f(.)$ 

In addition **boldfaced** letters are used to denote vectors. 

# Error model

$$
\Large
\boxed{\theta_1^∗(x) = P \circledast \theta_1(x) + (\RE\,N)^{−1}(E_1(x) + E_2(x))}
$$
where
$$
\begin{align*}
E_{1;p}(x) &= \RE\, S^{(1,0)}_{\text{resid};p} \circledast 1(x)\\
E_{2;p}(x) &= \RE\sum_q S^{(1,1)}_{\text{resid};p,q} \circledast \theta_{1,q}(x)
\end{align*}
$$

We define the errors 
$$
\large
\begin{align*}
&\epsilon_1 = (\RE\,N)^{-1}E_1(x)\\
&\small\text{Taking the Fourier transform on both sides we get}\\
&\Rightarrow \widehat{\epsilon_1}(k)_p = \E_1(k)_p \small\text{ where, }\quad \E_1(k)_p =\sum_r(\RE\,N)^{-1}_{p,r}\widehat{S}^{(1,0)}_{resid;r}(k)\\
\\
&\small\text{and,}\\
&\epsilon_2 = (\RE\,N)^{-1}E_2(x)\\
&\small\text{Taking the Fourier transform}\\
&\Rightarrow \widehat{\epsilon_2}(k)_p = \sum_{q}\E_2(k)_{p,q}\widehat{\theta_1}(k)_q \small\text{ where, }\quad
\E_2(k)_{p,q} = \sum_r (\RE\,N)^{-1}_{p,r}\widehat{S}^{(1,1)}_{\text{resid; }r,q}(k)
\end{align*}
$$

**Supplementary equations**
$$
\begin{align*}
S^{(1,1)}_{\text{resid};p,q}(x) &= \sum^{N_I}_{j=1}(P_j (x) − P(x))\overline{\D M(\theta_0)_{j;p}}\D M(\theta_0)_{j;q}\\
S^{(1,0)}_{\text{resid};p}(x) &= \sum^{N_I}_{j=1}(P_j (x) − P(x))\overline{\D M(\theta_0)_{j;p}}M(\theta_0)_j
\end{align*}
$$

# Assumption
1. We assume that the magnetization $M_j(\theta)$ is artifically rescaled by a scaling factor $\kappa_j$ that changes the relative weight of each signal in the image. 
\begin{align*}
\large
M_j^{(new)}(\theta) = \kappa_j\cdot M_j^{(old)}(\theta)
\end{align*}
2. ~Since $\widehat{\theta_1}(k)$ are tissue parameters of fixed size ($n$) and can assume random values. Therefore, $\widehat{\theta_1}(k)$ is assumed to be independent of $k$ and $q$~.  

### Compute $(\RE \,N)^{-1}$
The elements of matrix $\large N$ are found using
$$
\begin{align*}
N_{p,q} = \sum_{j=1}^{N_I} \overline{\mathcal{D}M(\theta_0)_{j;p}}\mathcal{D}M(\theta_0)_{j;q}\\
\end{align*}
$$

<!-- $$
\begin{align*}
N_{1,1} &= \sum_{j=1}^{N_I}\kappa_j^2\left.\overline{\frac{\partial M_j}{\partial T_1}}\right\rvert_{\theta=\theta_0}\left.\frac{\partial M_j}{\partial T_1}\right\rvert_{\theta=\theta_0}\\
&= \sum_{j=1}^{N_I}\kappa_j^2\left|\frac{\partial M_j}{\partial T_1}\right|_{\theta=\theta_0}^2\\
N_{1,2} &= \sum_{j=1}^{N_I}\kappa_j^2\left.\overline{\frac{\partial M_j}{\partial T_1}}\right\rvert_{\theta=\theta_0}\left.\frac{\partial M_j}{\partial T_2}\right\rvert_{\theta=\theta_0}
\end{align*}
$$ 
Values for $N_{2,1}$ and $N_{2,2}$ can be found similarly.-->  

For $3$ parameter case, the matrix expansion of $\large N$ would give the following $3\times3$ matrix
$$
\large
\begin{equation*}
N =
\begin{bmatrix}
\sum\limits_{j=1}^{N_I}\kappa_j^2\left|\frac{\partial M_j}{\partial T_1}\right|_{\theta=\theta_0}^2 & \sum\limits\limits_{j=1}^{N_I}\kappa_j^2\left.\overline{\frac{\partial M_j}{\partial T_1}}\right\rvert_{\theta=\theta_0}\left.\frac{\partial M_j}{\partial T_2}\right\rvert_{\theta=\theta_0} & \sum\limits_{j=1}^{N_I}\kappa_j^2\left.\overline{\frac{\partial M_j}{\partial T_1}}\right\rvert_{\theta=\theta_0}\left.\frac{\partial M_j}{\partial \rho}\right\rvert_{\theta=\theta_0}\\
\sum\limits_{j=1}^{N_I}\kappa_j^2\left.\overline{\frac{\partial M_j}{\partial T_2}}\right\rvert_{\theta=\theta_0}\left.\frac{\partial M_j}{\partial T_1}\right\rvert_{\theta=\theta_0} & \sum\limits_{j=1}^{N_I}\kappa_j^2\left|\frac{\partial M_j}{\partial T_2}\right|_{\theta=\theta_0}^2 & \sum\limits_{j=1}^{N_I}\kappa_j^2\left.\overline{\frac{\partial M_j}{\partial T_2}}\right\rvert_{\theta=\theta_0}\left.\frac{\partial M_j}{\partial \rho}\right\rvert_{\theta=\theta_0}\\
\sum\limits_{j=1}^{N_I}\kappa_j^2\left.\overline{\frac{\partial M_j}{\partial \rho}}\right\rvert_{\theta=\theta_0}\left.\frac{\partial M_j}{\partial T_1}\right\rvert_{\theta=\theta_0} & \sum\limits_{j=1}^{N_I}\kappa_j^2\left.\overline{\frac{\partial M_j}{\partial \rho}}\right\rvert_{\theta=\theta_0}\left.\frac{\partial M_j}{\partial T_2}\right\rvert_{\theta=\theta_0} & \sum\limits_{j=1}^{N_I}\kappa_j^2\left|\frac{\partial M_j}{\partial \rho}\right|_{\theta=\theta_0}^2
\end{bmatrix}_{3\times3}
\label{eq:N} \tag{1}
\end{equation*}
$$

We then find $\RE\,N$ and compute its *matrix inverse* to get $(\RE\,N)^{-1}$

<!-- ### Compute $\widehat{S}^{(1,0)}_{resid;r}(\zeta)$

$$
\begin{align*}
S^{(1,0)}_{\text{resid};p}(x) &= \sum^{N_I}_{j=1}(P_j (x) − P(x))\overline{\D M(\theta_0)_{j;p}}M(\theta_0)_j\\
\widehat{S}^{(1,0)}_{resid;r}(\zeta) &=\sum_{j=1}^{N_I}(\widehat{P_j(0)}-\widehat{P(0)})\overline{\D M(\theta_0)_{j;r}}M(\theta_0)_j\\
\end{align*}
$$ -->

### Compute $\widehat{S}^{(1,1)}_{\text{resid; }r,q}(\zeta)$
$$
\begin{align*}
\large
S^{(1,1)}_{\text{resid; }p,q}(x)&=\sum_{j=1}^{N_I} (P_j(x)-P(x))\overline{\mathcal{D}M(\theta_0)_{j;p}}\mathcal{D}M(\theta_0)_{j;q}\\
\large
\hat{S}^{(1,1)}_{\text{resid; }p,q}(\zeta) &= \mathcal{F}\left\{\sum_{j=1}^{N_I} (P_j(x)-P(x))\overline{\mathcal{D}M(\theta_0)_{j;p}}\mathcal{D}M(\theta_0)_{j;q}\right\}(\zeta)\\
\large
\Rightarrow\hat{S}^{(1,1)}_{\text{resid; }p,q}(\zeta) &= \sum_{j=1}^{N_I} \left(\widehat{P_j}(\zeta)-\widehat{P}(\zeta)\right)\overline{\mathcal{D}M(\theta_0)_{j;p}}\mathcal{D}M(\theta_0)_{j;q} 
\end{align*}
$$

For $3$ parameter case, the matrix $\large S^{(1,1)}_{\text{resid}}(\zeta)$ would be given as
$$
\begin{equation*}
S^{(1,1)}_{\text{resid}}(\zeta) =
\begin{bmatrix}
\sum\limits_{j=1}^{N_I}\kappa_j^2\left(\widehat{P_j}(\zeta)-\widehat{P}(\zeta)\right)\left|\frac{\partial M_j}{\partial T_1}\right|_{\theta=\theta_0}^2 & \sum\limits\limits_{j=1}^{N_I}\kappa_j^2\left(\widehat{P_j}(\zeta)-\widehat{P}(\zeta)\right)\left.\overline{\frac{\partial M_j}{\partial T_1}}\right\rvert_{\theta=\theta_0}\left.\frac{\partial M_j}{\partial T_2}\right\rvert_{\theta=\theta_0} & \sum\limits_{j=1}^{N_I}\kappa_j^2\left(\widehat{P_j}(\zeta)-\widehat{P}(\zeta)\right)\left.\overline{\frac{\partial M_j}{\partial T_1}}\right\rvert_{\theta=\theta_0}\left.\frac{\partial M_j}{\partial \rho}\right\rvert_{\theta=\theta_0}\\
\sum\limits_{j=1}^{N_I}\kappa_j^2\left(\widehat{P_j}(\zeta)-\widehat{P}(\zeta)\right)\left.\overline{\frac{\partial M_j}{\partial T_2}}\right\rvert_{\theta=\theta_0}\left.\frac{\partial M_j}{\partial T_1}\right\rvert_{\theta=\theta_0} & \sum\limits_{j=1}^{N_I}\kappa_j^2\left(\widehat{P_j}(\zeta)-\widehat{P}(\zeta)\right)\left|\frac{\partial M_j}{\partial T_2}\right|_{\theta=\theta_0}^2 & \sum\limits_{j=1}^{N_I}\kappa_j^2\left(\widehat{P_j}(\zeta)-\widehat{P}(\zeta)\right)\left.\overline{\frac{\partial M_j}{\partial T_2}}\right\rvert_{\theta=\theta_0}\left.\frac{\partial M_j}{\partial \rho}\right\rvert_{\theta=\theta_0}\\
\sum\limits_{j=1}^{N_I}\kappa_j^2\left(\widehat{P_j}(\zeta)-\widehat{P}(\zeta)\right)\left.\overline{\frac{\partial M_j}{\partial \rho}}\right\rvert_{\theta=\theta_0}\left.\frac{\partial M_j}{\partial T_1}\right\rvert_{\theta=\theta_0} & \sum\limits_{j=1}^{N_I}\kappa_j^2\left(\widehat{P_j}(\zeta)-\widehat{P}(\zeta)\right)\left.\overline{\frac{\partial M_j}{\partial \rho}}\right\rvert_{\theta=\theta_0}\left.\frac{\partial M_j}{\partial T_2}\right\rvert_{\theta=\theta_0} & \sum\limits_{j=1}^{N_I}\kappa_j^2\left(\widehat{P_j}(\zeta)-\widehat{P}(\zeta)\right)\left|\frac{\partial M_j}{\partial \rho}\right|_{\theta=\theta_0}^2
\end{bmatrix}_{3\times3}
\end{equation*}
$$


### General form of  $\widehat{\epsilon_1}(\zeta)$ terms

$$
\begin{align*}
&\widehat{\epsilon_1}(\zeta)_p =\quad \E_1(\zeta)_p =\sum_r(\RE\,N)^{-1}_{p,r}\widehat{S}^{(1,0)}_{resid;r}(\zeta)\delta(\zeta)\\
&\text{where, }\delta(\zeta) \text{ is the delta function which is 0 }\forall \zeta\neq0\\
&\text{for } \zeta=0 \text{ , }\delta(\zeta)=1\text{(assumed for simplicity) and the above expression reduces to}\\
&\large \widehat{\epsilon_1}(\zeta)_p =\sum_r(\RE\,N)^{-1}_{p,r}\widehat{S}^{(1,0)}_{resid;r}(0)\\
&\text{where, }\\
&\small \widehat{S}^{(1,0)}_{resid;r}(0)=\sum_{j=1}^{N_I}(\widehat{P_j(0)}-\widehat{P(0)})\overline{\D M(\theta_0)_{j;r}}M(\theta_0)_j
\end{align*}
$$

Expanding the $\widehat{S}^{(1,0)}_{resid;r}(0)$ for $r=1,2,3$ we get,
$$
\begin{align*}
\widehat{S}^{(1,0)}_{resid;1}(0) &= \sum_{j=1}^{N_I}\kappa_j^2\left(\widehat{P_j(0)}-\widehat{P(0)}\right)\left.\frac{\partial M_j}{\partial T_1}\right\rvert_{\theta=\theta_0}M_j(\theta_0)\\
\widehat{S}^{(1,0)}_{resid;2}(0) &= \sum_{j=1}^{N_I}\kappa_j^2\left(\widehat{P_j(0)}-\widehat{P(0)}\right)\left.\frac{\partial M_j}{\partial T_2}\right\rvert_{\theta=\theta_0}M_j(\theta_0)\\
\widehat{S}^{(1,0)}_{resid;3}(0) &= \sum_{j=1}^{N_I}\kappa_j^2\left(\widehat{P_j(0)}-\widehat{P(0)}\right)\left.\frac{\partial M_j}{\partial \rho}\right\rvert_{\theta=\theta_0}M_j(\theta_0)
\end{align*}
$$
So the general form of  $\widehat{\epsilon_{1;p}}(\zeta)$ is given by

$$
\begin{equation*}
\widehat{\epsilon_{1;p}}(\boldsymbol\kappa) = (\RE\,N)^{-1}_{p,1}\widehat{S}^{(1,0)}_{resid;1}(0)+(\RE\,N)^{-1}_{p,2}\widehat{S}^{(1,0)}_{resid;2}(0) + (\RE\,N)^{-1}_{p,3}\widehat{S}^{(1,0)}_{resid;3}(0)\\
\end{equation*}
$$

$$
\large
\begin{align*}
\Rightarrow\widehat{\epsilon_{1;p}}(\boldsymbol\kappa) &= (\RE\,N)^{-1}_{p,1}\sum_{j=1}^{N_I}\kappa_j^2\left(\widehat{P_j(0)}-\widehat{P(0)}\right)\left.\frac{\partial M_j}{\partial T_1}\right\rvert_{\theta=\theta_0}M_j(\theta_0) \\ 
&+(\RE\,N)^{-1}_{p,2}\sum_{j=1}^{N_I}\kappa_j^2\left(\widehat{P_j(0)}-\widehat{P(0)}\right)\left.\frac{\partial M_j}{\partial T_2}\right\rvert_{\theta=\theta_0}M_j(\theta_0) \\ 
&+(\RE\,N)^{-1}_{p,3}\sum_{j=1}^{N_I}\kappa_j^2\left(\widehat{P_j(0)}-\widehat{P(0)}\right)\left.\frac{\partial M_j}{\partial \rho}\right\rvert_{\theta=\theta_0}M_j(\theta_0)
\end{align*}\tag{2}
$$


### General form of  $\widehat{\epsilon_2}(\zeta)$ terms
$$
\widehat{\epsilon_{2;p}}(\zeta) = \sum_{q}\E_{2}(\zeta)_{p,q}\widehat{\theta_1}(\zeta)_q \small\text{ where, }\quad
\E_2(\zeta)_{p,q} = \sum_r (\RE\,N)^{-1}_{p,r}\widehat{S}^{(1,1)}_{\text{resid; }r,q}(\zeta)
$$

$$
\begin{align*}
\widehat{\epsilon_{2;p}}(\zeta) &= \sum_q \widehat{\theta_{1;q}}(\zeta)\sum_r (\RE\,N)^{-1}_{p,r}\widehat{S}^{(1,1)}_{\text{resid; }r,q}(\zeta)\\
&= \sum_q \widehat{\theta_{1;q}}(\zeta)\left\{(\RE\,N)^{-1}_{p,1}\widehat{S}^{(1,1)}_{\text{resid; }1,q}(\zeta)+(\RE\,N)^{-1}_{p,2}\widehat{S}^{(1,1)}_{\text{resid; }2,q}(\zeta)+(\RE\,N)^{-1}_{p,3}\widehat{S}^{(1,1)}_{\text{resid; }3,q}(\zeta)\right\}
\end{align*}
$$

$$
\large
\begin{align*}
\Rightarrow\widehat{\epsilon_{2;p}}(\boldsymbol{\zeta,\kappa}) &= \widehat{\theta_{1;1}}(\zeta)\left\{(\RE\,N)^{-1}_{p,1}\widehat{S}^{(1,1)}_{\text{resid; }1,1}(\zeta)+(\RE\,N)^{-1}_{p,2}\widehat{S}^{(1,1)}_{\text{resid; }2,1}(\zeta)+(\RE\,N)^{-1}_{p,3}\widehat{S}^{(1,1)}_{\text{resid; }3,1}(\zeta) \right\}\\
&+ \widehat{\theta_{1;2}}(\zeta)\left\{(\RE\,N)^{-1}_{p,1}\widehat{S}^{(1,1)}_{\text{resid; }1,2}(\zeta)+(\RE\,N)^{-1}_{p,2}\widehat{S}^{(1,1)}_{\text{resid; }2,2}(\zeta)+(\RE\,N)^{-1}_{p,3}\widehat{S}^{(1,1)}_{\text{resid; }3,2}(\zeta) \right\}\\
&+ \widehat{\theta_{1;3}}(\zeta)\left\{(\RE\,N)^{-1}_{p,1}\widehat{S}^{(1,1)}_{\text{resid; }1,3}(\zeta)+(\RE\,N)^{-1}_{p,2}\widehat{S}^{(1,1)}_{\text{resid; }2,3}(\zeta)+(\RE\,N)^{-1}_{p,3}\widehat{S}^{(1,1)}_{\text{resid; }3,3}(\zeta) \right\}
\end{align*}\tag{3}
$$

**Note:** In the above equation, once we plug in the values from the $S^{(1,1)}_{\text{resid}}(\zeta)$ matrix, the $\boldsymbol\kappa$ dependence is evident. It is omitted for simpler notations. 


<!-- For a particular $k$-space cordinate $\zeta$ and $n$ number of parameters the $(r,c)$ element of matrix $\E_2$ is given as
$$
\begin{align*}\label{eq:E3}
\large
\boxed{\E_2(\zeta;\boldsymbol\kappa)_{r,c} = (\RE\,N)^{-1}_{r,1}\hat{S}^{(1,1)}_{\text{resid};1,c}(\zeta) + (\RE\,N)^{-1}_{r,2}\hat{S}^{(1,1)}_{\text{resid};2,c}(\zeta) \ldots + (\RE\,N)^{-1}_{r,n}\hat{S}^{(1,1)}_{\text{resid};n,c}(\zeta)}
\end{align*}
$$ -->

### Some observations
- While $\widehat{\epsilon_{2;p}}(\boldsymbol{\zeta,\kappa})$ depends on $\boldsymbol{\zeta,\kappa}$, the $\widehat{\epsilon_{1;p}}(\boldsymbol\kappa)$ term depends only on $\boldsymbol\kappa$.
- The terms $(\RE\,N)^{-1}_{p,1},(\RE\,N)^{-1}_{p,2},(\RE\,N)^{-1}_{p,3}$ form the p<sup>th</sup> row of matrix $(\RE\,N)^{-1}$. 
- Similarly, the terms $\hat{S}^{(1,1)}_{\text{resid};1,1}(\zeta),\hat{S}^{(1,1)}_{\text{resid};2,1}(\zeta),\hat{S}^{(1,1)}_{\text{resid};3,1}(\zeta)$ form the 1<sup>st</sup> column of matrix $\hat{S}^{(1,1)}_{\text{resid}}(\zeta)$. 

## Minimizing the errors:

We denote the overall error $\widehat{\epsilon_1}+\widehat{\epsilon_2}$ at each $k$-space location as  
$$
\large
\G(\boldsymbol\zeta;\boldsymbol\kappa) = 
\begin{bmatrix}
\G_1(\boldsymbol{\zeta;\kappa})\\
\G_2(\boldsymbol{\zeta;\kappa})\\
\G_3(\boldsymbol{\zeta;\kappa})
\end{bmatrix}
= 
\begin{bmatrix}
\widehat{\epsilon_{1;1}}(\boldsymbol\kappa)+\widehat{\epsilon_{2;1}}(\boldsymbol{\zeta,\kappa})\\
\widehat{\epsilon_{1;2}}(\boldsymbol\kappa)+\widehat{\epsilon_{2;2}}(\boldsymbol{\zeta,\kappa})\\
\widehat{\epsilon_{1;3}}(\boldsymbol\kappa)+\widehat{\epsilon_{2;3}}(\boldsymbol{\zeta,\kappa})
\end{bmatrix}
\quad\small\text{substitute values from equation 2 & 3}
$$

**Few things to note** 
- $\G_i(\boldsymbol\zeta;\boldsymbol\kappa)$ is the error in the specific parameter $i$. So $\G_1(\boldsymbol\zeta;\boldsymbol\kappa)$ is the error in $T_1$.
- $\boldsymbol\kappa = \begin{bmatrix} \kappa_1 & \kappa_2 & \dots &\kappa_{N_I}\end{bmatrix}$
- $\boldsymbol\zeta = \begin{bmatrix} \zeta_1 & \zeta_2 & \dots & \zeta_{N_k} \end{bmatrix}$

### Some thoughts on moving ahead
- If we assume the errors are additive then the overall error $\boldsymbol\OG$ is given by
$$
\large
\boldsymbol\OG =
\begin{bmatrix}
\OG_1\\
\OG_2\\
\OG_3
\end{bmatrix}
=
\begin{bmatrix}
\G_1(\boldsymbol{\zeta_1,\kappa})+\G_1(\boldsymbol{\zeta_2,\kappa})+\dots+\G_1(\boldsymbol{\zeta_{N_k},\kappa})\\
\G_2(\boldsymbol{\zeta_1,\kappa})+\G_2(\boldsymbol{\zeta_2,\kappa})+\dots+\G_2(\boldsymbol{\zeta_{N_k},\kappa})\\
\G_3(\boldsymbol{\zeta_1,\kappa})+\G_3(\boldsymbol{\zeta_2,\kappa})+\dots+\G_3(\boldsymbol{\zeta_{N_k},\kappa})
\end{bmatrix}
$$

where, $\OG_1=\G_1(\boldsymbol{\zeta_1,\kappa})+\G_2(\boldsymbol{\zeta_2,\kappa})+\dots+\G_{N_k}(\boldsymbol{\zeta_{N_k},\kappa})$

Ideally we want the errors to be zero for each parameter. So we can try to find a solution to $\kappa$ for 
$$
\OG(\boldsymbol{\kappa})=
\begin{bmatrix}
0\\
0\\
0\\
\end{bmatrix}
$$

Taking the Jacobian of the overall error
$$
\large
\begin{align*}
\D \Gamma =
\begin{bmatrix}
\frac{\partial\OG_1}{\partial \kappa_1} & \dots & \frac{\partial\OG_1}{\partial \kappa_{N_I}}\\
\frac{\partial\OG_2}{\partial \kappa_1} & \dots & \frac{\partial\OG_2}{\partial \kappa_{N_I}}\\
\frac{\partial\OG_3}{\partial \kappa_1} & \dots & \frac{\partial\OG_3}{\partial \kappa_{N_I}}
\end{bmatrix}_{3\times N_I}
\end{align*}
$$

## Solving non linear equations using [NLSolve.jl](https://github.com/JuliaNLSolvers/NLsolve.jl)

Consider a vector valued function $F(x,y)$

$F(x, y) = \begin{bmatrix}(x+3)(y^3-7)+18 & \sin(ye^x-1)\end{bmatrix}$


In [2]:
import Pkg
Pkg.add("NLsolve")

    Updating registry at `C:\Users\Kamlesh\.julia\registries\General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
   Installed FiniteDiff ──── v2.11.0
   Installed NLSolversBase ─ v7.8.2
   Installed LineSearches ── v7.1.1
   Installed NLsolve ─────── v4.5.1
    Updating `C:\Users\Kamlesh\.julia\environments\v1.7\Project.toml`
  [2774e3e8] + NLsolve v4.5.1
    Updating `C:\Users\Kamlesh\.julia\environments\v1.7\Manifest.toml`
  [6a86dc24] + FiniteDiff v2.11.0
  [d3d80556] + LineSearches v7.1.1
  [d41bc354] + NLSolversBase v7.8.2
  [2774e3e8] + NLsolve v4.5.1
Precompiling project...
  ✓ FiniteDiff
  ✓ NLSolversBase
  ✓ LineSearches
  ✓ NLsolve
  4 dependencies successfully precompiled in 12 seconds (316 already precompiled)


In [3]:
using NLsolve

#computes the residuals of the nonlinear system,and stores them in a preallocated vector passed as first argument
function f!(F, x)
    F[1] = (x[1]+3)*(x[2]^3-7)+18
    F[2] = sin(x[2]*exp(x[1])-1)
end

#computes the Jacobian of the system and stores it in a preallocated matrix passed as first argument. 
function j!(J, x)
    J[1, 1] = x[2]^3-7
    J[1, 2] = 3*x[2]^2*(x[1]+3)
    u = exp(x[1])*cos(x[2]*exp(x[1])-1)
    J[2, 1] = x[2]*u
    J[2, 2] = u
end

nlsolve(f!, j!, [ 0.1; 1.2])

Results of Nonlinear Solver Algorithm
 * Algorithm: Trust-region with dogleg and autoscaling
 * Starting Point: [0.1, 1.2]
 * Zero: [-3.487552479724522e-16, 1.0000000000000002]
 * Inf-norm of residuals: 0.000000
 * Iterations: 4
 * Convergence: true
   * |x - x'| < 0.0e+00: false
   * |f(x)| < 1.0e-08: true
 * Function Calls (f): 5
 * Jacobian Calls (df/dx): 5

## Some drafts

### Objective functions: 

1. $$\min \underset{k,p,q}{\max}\E_2(k)_{p,q}$$ 

2. <u>*Least square formulation*</u>  
Minimization in least square sense is given by
$$
\large
argmin_\beta\sum_{i=1}^m\left[v_i -f(u_i;\boldsymbol\beta) \right]^2
$$

 In our case the residuals $v_i -f(u_i;\boldsymbol\beta)=\E_2(\zeta;\boldsymbol\kappa)_{r,c}$

$$
\large
\therefore\quad argmin_\boldsymbol\kappa\sum_{r,c}\left[ \E_2(\zeta;\boldsymbol\kappa)_{r,c}\right]^2
$$
**To-Do:** Include $\E_1$ terms as well.

### Minimization

For the above objective function, we construct a vector $E$ with elements as the individual $\E_2$ terms found from equation $(2)$ and compute its jacobian $\D E$. For the general case of $n=3$ parameters and a $k-$space grid of size $[m_1\times m_2]$, $E$ and $\D E$ are given as:

$$
\begin{align*}\label{eq:resid}\tag{3}
\large
E =
\begin{bmatrix}
\E_2(kx_1,ky_1)_{1,1}\\
\vdots\\
\E_2(kx_{m_1},ky_{m_2})_{3,1}\\
\E_2(kx_1,ky_1)_{1,2}\\
\vdots\\
\E_2(kx_{m_1},ky_{m_2})_{3,2}\\
\E_2(kx_1,ky_1)_{1,3}\\
\vdots\\
\E_2(kx_{m_1},ky_{m_2})_{3,3}
\end{bmatrix}
\end{align*}
$$

$$
\large
\begin{align*}
\D E =
\begin{bmatrix}
\frac{\partial\E_2(kx_1,ky_1)_{1,1}}{\partial \kappa_1} & \dots & \frac{\partial\E_2(kx_1,ky_1)_{1,1}}{\partial \kappa_{N_I}}\\
\vdots & \ddots & \vdots\\
\frac{\partial\E_2(kx_{m_1},ky_{m_2})_{3,3}}{\partial \kappa_1} & \dots & \frac{\partial\E_2(kx_{m_1},ky_{m_2})_{3,3}}{\partial \kappa_{N_I}}
\end{bmatrix}
\end{align*}
$$

**Note** that $\E_2$ has $3\times3=9$ elements for each $k$-space coordinate. $\therefore$ the length of vector $E$ is $9m_1m_2$ and the size of jacobian $\D E$ is $9m_1m_2 \times N_I$.  

### Least square formulation for $\large\OG$
Ideally we want the errors to be zero for each parameter. So we can minimize
$$
\begin{align*}
&\left\{(0-\OG_1)^2+(0-\OG_2)^2+(0-\OG_3)^2\right\}\\
\\
&\text{taking derivative w.r.t to } \kappa\text{ we get } N_I \text{ gradient equations}\\
\\
\Rightarrow&2\left\{\OG_1\frac{\partial\OG_1}{\partial\kappa_1} + \OG_2\frac{\partial\OG_2}{\partial\kappa_1} + \OG_3\frac{\partial\OG_3}{\partial\kappa_1}\right\}=0\\
&2\left\{\OG_1\frac{\partial\OG_1}{\partial\kappa_2} + \OG_2\frac{\partial\OG_2}{\partial\kappa_2} + \OG_3\frac{\partial\OG_3}{\partial\kappa_2}\right\}=0\\
&\vdots\\
&2\left\{\OG_1\frac{\partial\OG_1}{\partial\kappa_{N_I}} + \OG_2\frac{\partial\OG_2}{\partial\kappa_{N_I}} + \OG_3\frac{\partial\OG_3}{\partial\kappa_{N_I}}\right\}=0
\end{align*}
$$

Since the terms $\OG_i\frac{\partial\OG_i}{\partial\kappa_j}$ have degree $>1$ in $\kappa_j$, the above system of equations are non-linear in $\kappa_j$. 

## Guass-Newton algorithm (GNA)
Given a set of $m$ empirical observations $(u_i,v_i)$ of independent and dependent variables, the parameter vector $\boldsymbol\beta$ of the *model curve* $\mathbf{f}(\boldsymbol{u;\beta})$ is estimated using the iterative algorithm:

> ### Algorithm
>
> 1. Start with an initial guess for $\boldsymbol{\beta}$.
> 2. Compute the residual vector $\left[\mathbf {v} -\mathbf {f} \left({\boldsymbol {u;\beta}}\right)\right]\quad\forall(x,y)$
> 3. Compute the Jacobian matrix $\mathbf{J}$ using $\boldsymbol{\beta}$ and $x_i$.
> 4. Solve for $\boldsymbol {\delta }$: $\mathbf{J}^{\mathrm {T}}\mathbf {J} {\boldsymbol {\delta }}=\mathbf {J} ^{\mathrm {T} }\left[\mathbf {v} -\mathbf {f} \left({\boldsymbol {u;\beta }}\right)\right],$ where $\boldsymbol {\delta }$ is the parameter correction vector
> 5. Update the parameter ${\boldsymbol {\beta }} = {\boldsymbol {\beta }} + \boldsymbol {\delta }$ and iterate till stopping criterion is reached.

In our case:
- The $\mathbf{f}$ is ??
- The residual vector in step 2 is given by equation $(3)$.
- parameter $\boldsymbol{\beta}$ is the vector of scaling factors $\boldsymbol\kappa=[\kappa_1,\kappa_2,\dots,\kappa_{N_I}]$ 
- $u_i$ corresponds to a k-space point $(kx_i, ky_i)$.
- what are the $v_i$??

## Levenberg–Marquardt algorithm (LMA)
> Change the equation in step 4 of GNA to ${\displaystyle \left[\mathbf {J} ^{\mathrm {T} }\mathbf {J} +\lambda \operatorname {diag} \left(\mathbf {J} ^{\mathrm {T} }\mathbf {J} \right)\right]{\boldsymbol {\delta }}=\mathbf {J} ^{\mathrm {T} }\left[\mathbf {y} -\mathbf {f} \left({\boldsymbol {\beta }}\right)\right],}$ where $\lambda$ is a damping factor.

## Julia implementations 

### LMA
The library [LsqFit.jl](https://julianlsolvers.github.io/LsqFit.jl/latest/getting_started/) implements the LMA algorithm using 
`curve_fit()` function. The call to the function looks like:
```julia
fit = curve_fit(model, [jacobian], x, y, [w,] p0; kwargs...)
``` 
- `model`: function that takes two arguments (x, params)
- `jacobian`: (optional) function that returns the Jacobian matrix of model
- `x`: the independent variable
- `y`: the dependent variable that constraints model
- `w`: (optional) weight applied to the residual; can be a vector (of length(x) size or empty) or matrix (inverse covariance  matrix)
- `p0`: initial guess of the model parameters
- `kwargs`: tuning parameters for fitting, passed to levenberg_marquardt, such as maxIter, show_trace or lower and upper bounds

If a Jacobian is not provided, the central finite difference scheme is used to approximate the Jacobian. It is also possible to use forward mode automatic differentiation as implemented in [ForwardDiff.jl](https://juliadiff.org/ForwardDiff.jl/stable/) by using the `autodiff=:forwarddiff` keyword.

### BFGS
The library [Optim.jl](https://julianlsolvers.github.io/Optim.jl/stable/#user/minimization/) has the option to use BFGS algorithm.
```julia
Optim.minimizer(optimize(f, initial_x, BFGS(); autodiff = :forward))
``` 

In [ ]:
# from importlib.metadata import version
# from platform import python_version

# print(python_version())
# version('numpy')
# import numpy as np
# x = np.array([1, 2.5, 3.5, 4, 5, 7, 8.5])
# x[:,np.newaxis]**[0,2]

## Cross talk error term $\mathcal{E}_2$
\begin{align*}
\Large
\mathcal{E}_2(k)_{p,q} = \sum_r (\RE\,N)^{-1}_{p,r}\hat{S}^{(1,1)}_{\text{resid; }r,q}(k)
\end{align*}
$\mathcal{E}_2(k)_{p,q}$ is a $N_p\times N_p$ matrix for each $k$

### For $n=3$ parameter case ($T_1, T_2$ and $\rho$)  


So we have $3\times3=9$ entries for each $k$-space coordinate. For a $k-$space grid of $[m_1\times m_2]$, we construct the vector $E$ with elements as the elements of the $\mathcal{E}$ matrix. Note that vector $E$ has a length of $9m_1m_2$.
$$
\begin{align*}
E =
\begin{bmatrix}
\mathcal{E}_2(kx_1,ky_1)_{1,1}\\
\vdots\\
\mathcal{E}_2(kx_{m_1},ky_{m_2})_{1,1}\\
\mathcal{E}_2(kx_1,ky_1)_{2,1}\\
\vdots\\
\mathcal{E}_2(kx_{m_1},ky_{m_2})_{2,1}\\
\mathcal{E}_2(kx_1,ky_1)_{3,1}\\
\vdots\\
\mathcal{E}_2(kx_{m_1},ky_{m_2})_{3,1}\\
\mathcal{E}_2(kx_1,ky_1)_{1,2}\\
\vdots\\
\mathcal{E}_2(kx_{m_1},ky_{m_2})_{1,2}\\
\mathcal{E}_2(kx_1,ky_1)_{2,2}\\
\vdots\\
\mathcal{E}_2(kx_{m_1},ky_{m_2})_{2,2}\\
\mathcal{E}_2(kx_1,ky_1)_{3,2}\\
\vdots\\
\mathcal{E}_2(kx_{m_1},ky_{m_2})_{3,2}\\
\mathcal{E}_2(kx_1,ky_1)_{1,3}\\
\vdots\\
\mathcal{E}_2(kx_{m_1},ky_{m_2})_{1,3}\\
\mathcal{E}_2(kx_1,ky_1)_{2,3}\\
\vdots\\
\mathcal{E}_2(kx_{m_1},ky_{m_2})_{2,3}\\
\mathcal{E}_2(kx_1,ky_1)_{3,3}\\
\vdots\\
\mathcal{E}_2(kx_{m_1},ky_{m_2})_{3,3}
\end{bmatrix}
\end{align*}
$$
*We now try to minimize the $\left\lVert E \right\rVert^2$, where $\left\lVert . \right\rVert$ is the $\ell_2$ norm*